# Generated by Django 5.1.5 on 2026-07-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("admin", "Admin"),
                    ("accountant", "Accountant"),
                    ("hr_manager", "HR Manager"),
                    ("registration_officer", "Registration Officer"),
                    ("cashier", "Cashier"),
                    ("teacher", "Teacher"),
                    ("viewer", "Viewer"),
                    ("employee", "Employee"),
                    ("customer", "Customer"),
                    ("vendor", "Vendor"),
                ],
                default="viewer",
                max_length=20,
            ),
        ),
    ]
