# Generated by Django 5.1.5 on 2026-06-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_calendar",
            field=models.CharField(
                choices=[
                    ("gregorian", "Gregorian (میلادی)"),
                    ("shamsi", "Shamsi (شمسی)"),
                    ("qamari", "Qamari (قمری)"),
                ],
                default="shamsi",
                max_length=20,
                verbose_name="Preferred Calendar",
            ),
        ),
    ]
