# Generated by Django 5.1.5 on 2026-06-08 12:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar ($)"),
                            ("AFN", "Afghan Afghani (؋)"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Class Fee",
                "verbose_name_plural": "Class Fees",
                "ordering": ["class_level__level", "fee_type__name"],
            },
        ),
        migrations.CreateModel(
            name="FeeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "name_fa",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="نام به دری"
                    ),
                ),
                (
                    "name_ps",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="نام به پښتو",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("admission", "Admission Fee"),
                            ("book", "Book Fee"),
                            ("uniform", "Uniform Fee"),
                            ("transportation", "Transportation Fee"),
                            ("exam", "Exam Fee"),
                            ("other", "Other Fee"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "description_fa",
                    models.TextField(
                        blank=True, null=True, verbose_name="توضیحات به دری"
                    ),
                ),
                (
                    "description_ps",
                    models.TextField(
                        blank=True, null=True, verbose_name="توضیحات به پښتو"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_mandatory", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Fee Type",
                "verbose_name_plural": "Fee Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FinanceLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Invoice Entry"),
                            ("payment", "Payment Entry"),
                            ("refund", "Refund Entry"),
                            ("adjustment", "Adjustment Entry"),
                            ("transfer", "Transfer Entry"),
                        ],
                        default="invoice",
                        max_length=20,
                    ),
                ),
                ("reference_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "account",
                    models.CharField(
                        help_text="Account code (e.g., receivable, income)",
                        max_length=100,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar ($)"),
                            ("AFN", "Afghan Afghani (؋)"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "entry_side",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "description_fa",
                    models.TextField(
                        blank=True, null=True, verbose_name="توضیحات به دری"
                    ),
                ),
                (
                    "description_ps",
                    models.TextField(
                        blank=True, null=True, verbose_name="توضیحات به پښتو"
                    ),
                ),
            ],
            options={
                "verbose_name": "Finance Ledger",
                "verbose_name_plural": "Finance Ledgers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "interval_months",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of months between payments"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Start date of payment plan",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="End date of payment plan (optional)",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Payment Plan",
                "verbose_name_plural": "Payment Plans",
                "ordering": ["student"],
            },
        ),
        migrations.CreateModel(
            name="StudentFeeAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar ($)"),
                            ("AFN", "Afghan Afghani (؋)"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("is_mandatory", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Student Fee Assignment",
                "verbose_name_plural": "Student Fee Assignments",
                "ordering": ["student", "fee_type__name"],
            },
        ),
        migrations.CreateModel(
            name="StudentInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar ($)"),
                            ("AFN", "Afghan Afghani (؋)"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "period_start",
                    models.DateField(
                        blank=True, help_text="Start of period", null=True
                    ),
                ),
                (
                    "period_end",
                    models.DateField(blank=True, help_text="End of period", null=True),
                ),
                (
                    "period_month",
                    models.CharField(
                        blank=True,
                        help_text="Period month (1-12)",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "period_year",
                    models.CharField(
                        blank=True, help_text="Period year", max_length=4, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("partial", "Partially Paid"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Student Invoice",
                "verbose_name_plural": "Student Invoices",
                "ordering": ["-due_date", "student", "fee_type"],
            },
        ),
        migrations.AlterModelOptions(
            name="studentpayment",
            options={
                "ordering": ["-payment_date"],
                "verbose_name": "Student Payment",
                "verbose_name_plural": "Student Payments",
            },
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="api_student_payment_0ddba4_idx",
        ),
        migrations.RemoveIndex(
            model_name="studentpayment",
            name="api_student_payment_766a95_idx",
        ),
        migrations.AddField(
            model_name="student",
            name="payment_interval_months",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of months between payments (1=monthly, 2=bimonthly, 3=quarterly, 12=yearly)",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="monthly_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="payment_cycle",
            field=models.CharField(
                blank=True,
                default="monthly",
                help_text="DEPRECATED: Use payment_interval_months",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="yearly_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="studentpayment",
            name="payment_cycle",
            field=models.CharField(
                blank=True,
                choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                default="monthly",
                help_text="DEPRECATED: Use student.payment_interval_months",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="studentpayment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_payments",
                to="api.student",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["payment_interval_months"],
                name="api_student_payment_3515db_idx",
            ),
        ),
        migrations.AddField(
            model_name="classfee",
            name="class_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_fees",
                to="api.classlevel",
            ),
        ),
        migrations.AddField(
            model_name="classfee",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feetype",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="classfee",
            name="fee_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_fee_levels",
                to="api.feetype",
            ),
        ),
        migrations.AddField(
            model_name="financeledger",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="financeledger",
            name="related_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="Related ledger entry (e.g., payment related to invoice)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_entries",
                to="api.financeledger",
            ),
        ),
        migrations.AddField(
            model_name="financeledger",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="api.student",
            ),
        ),
        migrations.AddField(
            model_name="paymentplan",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentplan",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_plan",
                to="api.student",
            ),
        ),
        migrations.AddField(
            model_name="studentfeeassignment",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentfeeassignment",
            name="fee_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_assignments",
                to="api.feetype",
            ),
        ),
        migrations.AddField(
            model_name="studentfeeassignment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_assignments",
                to="api.student",
            ),
        ),
        migrations.AddField(
            model_name="studentinvoice",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentinvoice",
            name="fee_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="api.feetype",
            ),
        ),
        migrations.AddField(
            model_name="studentinvoice",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="api.student",
            ),
        ),
        migrations.AddField(
            model_name="studentpayment",
            name="invoices",
            field=models.ManyToManyField(
                blank=True, related_name="payments", to="api.studentinvoice"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classfee",
            unique_together={("fee_type", "class_level")},
        ),
        migrations.AddIndex(
            model_name="financeledger",
            index=models.Index(
                fields=["student", "entry_type"], name="api_finance_student_7d9a10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financeledger",
            index=models.Index(
                fields=["account", "created_at"], name="api_finance_account_0fdab9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financeledger",
            index=models.Index(
                fields=["created_at"], name="api_finance_created_309207_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentfeeassignment",
            unique_together={("student", "fee_type")},
        ),
        migrations.AddIndex(
            model_name="studentinvoice",
            index=models.Index(
                fields=["student", "status"], name="api_student_student_45b9fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentinvoice",
            index=models.Index(
                fields=["due_date"], name="api_student_due_dat_fd92b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentinvoice",
            index=models.Index(
                fields=["period_year", "period_month"],
                name="api_student_period__ff22d6_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentinvoice",
            unique_together={("student", "fee_type", "period_month", "period_year")},
        ),
    ]
