# Generated by Django 5.1.5 on 2026-06-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="monthly_rent",
        ),
        migrations.RemoveField(
            model_name="shoprental",
            name="security_deposit",
        ),
    ]
