# Generated by Django 5.1.5 on 2026-06-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_shop_currency_remove_shop_monthly_rent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="class_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Class 1"),
                    ("2", "Class 2"),
                    ("3", "Class 3"),
                    ("4", "Class 4"),
                    ("5", "Class 5"),
                    ("6", "Class 6"),
                    ("7", "Class 7"),
                    ("8", "Class 8"),
                    ("9", "Class 9"),
                    ("10", "Class 10"),
                    ("11", "Class 11"),
                    ("12", "Class 12"),
                ],
                help_text="Class level the student is enrolled in",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="studentfeeassignment",
            name="class_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Class 1"),
                    ("2", "Class 2"),
                    ("3", "Class 3"),
                    ("4", "Class 4"),
                    ("5", "Class 5"),
                    ("6", "Class 6"),
                    ("7", "Class 7"),
                    ("8", "Class 8"),
                    ("9", "Class 9"),
                    ("10", "Class 10"),
                    ("11", "Class 11"),
                    ("12", "Class 12"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.RenameIndex(
            model_name="student",
            new_name="api_student_class_l_eac12c_idx",
            old_name="api_student_class_l_fea202_idx",
        ),
        migrations.DeleteModel(
            name="ClassLevel",
        ),
    ]
