# Generated by Django 5.1.5 on 2026-06-10 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_studentpayment_fee_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feetype",
            name="description_fa",
        ),
        migrations.RemoveField(
            model_name="feetype",
            name="description_ps",
        ),
        migrations.RemoveField(
            model_name="feetype",
            name="name_fa",
        ),
        migrations.RemoveField(
            model_name="feetype",
            name="name_ps",
        ),
        migrations.RemoveField(
            model_name="financeledger",
            name="description_fa",
        ),
        migrations.RemoveField(
            model_name="financeledger",
            name="description_ps",
        ),
        migrations.AddField(
            model_name="studentfeeassignment",
            name="class_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fee_assignments",
                to="api.classlevel",
            ),
        ),
        migrations.AddField(
            model_name="studentfeeassignment",
            name="payment_plan",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of months between payments for this assignment",
            ),
        ),
        migrations.AlterField(
            model_name="studentpayment",
            name="fee_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific fee type this payment covers (e.g., book, uniform)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_payments",
                to="api.feetype",
            ),
        ),
        migrations.DeleteModel(
            name="PaymentPlan",
        ),
    ]
