# Generated by Django 5.1.5 on 2026-06-17 10:04

from django.db import migrations, models


def convert_month_to_int(apps, schema_editor):
    """Convert existing month strings to integers"""
    month_map = {
        'january': 1, 'february': 2, 'march': 3, 'april': 4,
        'may': 5, 'june': 6, 'july': 7, 'august': 8,
        'september': 9, 'october': 10, 'november': 11, 'december': 12
    }
    
    # Convert Advance months
    Advance = apps.get_model('api', 'Advance')
    for advance in Advance.objects.all():
        if isinstance(advance.month, str):
            month_lower = advance.month.lower()
            if month_lower in month_map:
                advance.month = month_map[month_lower]
            elif advance.month.isdigit():
                advance.month = int(advance.month)
            else:
                advance.month = 1
            advance.save(update_fields=['month'])
    
    # Convert Payroll months
    Payroll = apps.get_model('api', 'Payroll')
    for payroll in Payroll.objects.all():
        if isinstance(payroll.month, str):
            month_lower = payroll.month.lower()
            if month_lower in month_map:
                payroll.month = month_map[month_lower]
            elif payroll.month.isdigit():
                payroll.month = int(payroll.month)
            else:
                payroll.month = 1
            payroll.save(update_fields=['month'])


def reverse_convert(apps, schema_editor):
    """Reverse migration - convert int to string"""
    month_names = ['', 'january', 'february', 'march', 'april', 'may', 'june',
                   'july', 'august', 'september', 'october', 'november', 'december']
    
    Advance = apps.get_model('api', 'Advance')
    for advance in Advance.objects.all():
        if isinstance(advance.month, int) and 1 <= advance.month <= 12:
            advance.month = month_names[advance.month]
            advance.save(update_fields=['month'])
    
    Payroll = apps.get_model('api', 'Payroll')
    for payroll in Payroll.objects.all():
        if isinstance(payroll.month, int) and 1 <= payroll.month <= 12:
            payroll.month = month_names[payroll.month]
            payroll.save(update_fields=['month'])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_student_class_level_and_more"),
    ]

    operations = [
        migrations.RunPython(convert_month_to_int, reverse_convert),
        migrations.AlterField(
            model_name='advance',
            name='month',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.PositiveIntegerField(),
        ),
    ]
