# Generated by Django 5.1.5 on 2026-06-10 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_feetype_description_fa_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentinvoice",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="studentinvoice",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="studentinvoice",
            name="fee_type",
        ),
        migrations.RemoveField(
            model_name="studentinvoice",
            name="student",
        ),
        migrations.RemoveField(
            model_name="studentpayment",
            name="invoices",
        ),
        migrations.RemoveIndex(
            model_name="studentpayment",
            name="api_student_student_6bbf0e_idx",
        ),
        migrations.RemoveField(
            model_name="studentpayment",
            name="student",
        ),
        migrations.AddField(
            model_name="studentpayment",
            name="assignment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="api.studentfeeassignment",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="studentpayment",
            index=models.Index(
                fields=["assignment", "payment_date"],
                name="api_student_assignm_c85ed7_idx",
            ),
        ),
        migrations.DeleteModel(
            name="StudentInvoice",
        ),
    ]
