# Generated by Django 5.1.5 on 2026-06-13 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_studentinvoice_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentfeeassignment",
            unique_together={("student", "fee_type", "class_level")},
        ),
    ]
