# Generated by Django 5.1.5 on 2026-07-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="fee_type",
            field=models.CharField(
                choices=[("paid", "Paid Student"), ("free", "Free Student")],
                default="paid",
                max_length=10,
            ),
        ),
    ]
