# Generated by Django 5.1.5 on 2026-06-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_populate_class_level_in_assignments"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="student",
            name="api_student_payment_3515db_idx",
        ),
        migrations.RemoveField(
            model_name="student",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="student",
            name="payment_interval_months",
        ),
        migrations.AlterField(
            model_name="student",
            name="payment_cycle",
            field=models.CharField(
                blank=True,
                default="monthly",
                help_text="DEPRECATED: Legacy field",
                max_length=10,
                null=True,
            ),
        ),
    ]
