# Generated by Django 5.1.5 on 2026-06-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_student_api_student_payment_3515db_idx_and_more"),
        ("api", "0009_shop_rental_payment_multimonth"),
    ]

    operations = []
